//SCRIPTED

//DECLARATIVE
pipeline {
	agent any
	stages {
		stage('Build') {
			steps {
				echo "Build"
				echo "Test"
				echo "Integration Test"
			}
		}
		stage('Test') {
			steps {
				echo "Test"
			}
		}
		stage('Integration Test') {
			steps {
				echo "Integration Test"
			}
		}
	} 
	
	post {
		always {
			echo "I am always running!"
		}
		success {
			echo "I run when you are succesfull!"
		}
		failure {
			echo "I run when you fail!"
		}
	}
}
